export const ENV = {
  BETTERMODE_CLIENT_ID: import.meta.env.VITE_BETTERMODE_CLIENT_ID as string,
  BETTERMODE_CLIENT_SECRET: import.meta.env.VITE_BETTERMODE_CLIENT_SECRET as string,
  BETTERMODE_SIGNING_SECRET: import.meta.env.VITE_BETTERMODE_SIGNING_SECRET as string,
};
